"""Tests for the AGENTS.md generator.

The generated file is fed back into the system prompt via
load_agent_instructions, so we deliberately keep its markdown sparse:
no bold/italic, no code fences for one-liners, no per-file import dumps.
"""

from __future__ import annotations

import asyncio

from squishy.index import _build_index_async
from squishy.index.agents_md import generate_agents_md


def _build(tmp_path):
    return asyncio.get_event_loop().run_until_complete(
        _build_index_async(str(tmp_path))
    )


def test_no_bold_or_italic_decoration(tmp_path):
    (tmp_path / "a.py").write_text("import os\nimport json\n")
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    # Bold uses **, italic uses single * around words. Plain prose only.
    assert "**" not in out
    # Tolerate dashes inside bullets (em dashes are fine), but not Markdown
    # italics. Use a simple heuristic: no `*` characters at all in the body
    # since the generator never emits them.
    assert "*" not in out


def test_no_python_code_fences_for_imports(tmp_path):
    """Per-file import dumps used to wrap every line in ```python ... ```;
    the new generator must not introduce that bloat."""
    (tmp_path / "a.py").write_text("import json\nimport requests\n")
    (tmp_path / "b.py").write_text("import json\nimport httpx\n")
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    assert "```python" not in out
    assert "```" not in out


def test_external_deps_section_is_deduped_one_line(tmp_path):
    (tmp_path / "a.py").write_text("import json\nimport requests\n")
    (tmp_path / "b.py").write_text("import json\nimport httpx\nimport requests\n")
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    assert "## External deps" in out
    # stdlib (json) and the package's own self-imports must not appear.
    deps_block = out.split("## External deps", 1)[1].split("##", 1)[0]
    assert "json" not in deps_block
    # External deps appear exactly once each on a single line.
    assert "requests" in deps_block
    assert "httpx" in deps_block
    assert deps_block.count("requests") == 1


def test_planning_workflow_has_no_nested_bold(tmp_path):
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    assert "## Planning workflow" in out
    # The block used to read "**Important**: ..." with bold mid-sentence.
    block = out.split("## Planning workflow", 1)[1]
    assert "**" not in block


def test_no_horizontal_rule_dividers(tmp_path):
    """The previous template wrapped the file in --- dividers and a final
    italic 'Generated by ...' footer that ate context for no signal."""
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    # No standalone --- lines
    for line in out.splitlines():
        assert line.strip() != "---"
    assert "Generated by squishy" not in out


def test_output_is_compact_for_a_small_repo(tmp_path):
    """Sanity check: a repo with one file should produce <2KB of output."""
    (tmp_path / "a.py").write_text("def hello():\n    pass\n")
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    assert len(out) < 2000
