"""Tests for the AGENTS.md generator.

The generated file is fed back into the system prompt via
load_agent_instructions, so we deliberately keep its markdown sparse:
no bold/italic, no code fences for one-liners, no per-file import dumps.
"""

from __future__ import annotations

import asyncio

from squishy.index import _build_index_async
from squishy.index.agents_md import generate_agents_md


def _build(tmp_path):
    # Drive the async indexer from a sync test: asyncio.run creates a
    # fresh loop, runs the coroutine to completion, and tears the loop
    # down. The previous get_event_loop() call relied on a running loop
    # that doesn't exist outside pytest-asyncio's coroutine tests.
    return asyncio.run(_build_index_async(str(tmp_path)))


def test_no_bold_or_italic_decoration(tmp_path):
    (tmp_path / "a.py").write_text("import os\nimport json\n")
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    # Bold uses **, italic uses single * around words. Plain prose only.
    assert "**" not in out
    # Tolerate dashes inside bullets (em dashes are fine), but not Markdown
    # italics. Use a simple heuristic: no `*` characters at all in the body
    # since the generator never emits them.
    assert "*" not in out


def test_no_python_code_fences_for_imports(tmp_path):
    """Per-file import dumps used to wrap every line in ```python ... ```;
    the new generator must not introduce that bloat."""
    (tmp_path / "a.py").write_text("import json\nimport requests\n")
    (tmp_path / "b.py").write_text("import json\nimport httpx\n")
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    assert "```python" not in out
    assert "```" not in out


def test_external_deps_section_is_deduped_one_line(tmp_path):
    (tmp_path / "a.py").write_text("import json\nimport requests\n")
    (tmp_path / "b.py").write_text("import json\nimport httpx\nimport requests\n")
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    assert "## External deps" in out
    # stdlib (json) and the package's own self-imports must not appear.
    deps_block = out.split("## External deps", 1)[1].split("##", 1)[0]
    assert "json" not in deps_block
    # External deps appear exactly once each on a single line.
    assert "requests" in deps_block
    assert "httpx" in deps_block
    assert deps_block.count("requests") == 1


def test_navigation_section_has_no_nested_bold(tmp_path):
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    assert "## Navigation" in out
    # The block used to read "**Important**: ..." with bold mid-sentence.
    block = out.split("## Navigation", 1)[1]
    assert "**" not in block


def test_no_horizontal_rule_dividers(tmp_path):
    """The previous template wrapped the file in --- dividers and a final
    italic 'Generated by ...' footer that ate context for no signal."""
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    # No standalone --- lines
    for line in out.splitlines():
        assert line.strip() != "---"
    assert "Generated by squishy" not in out


def test_output_is_compact_for_a_small_repo(tmp_path):
    """Sanity check: a repo with one file should produce <2KB of output."""
    (tmp_path / "a.py").write_text("def hello():\n    pass\n")
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    assert len(out) < 2000


def test_no_file_type_emojis_in_tree(tmp_path):
    """File-type emojis (🐍 📄 🦀 …) cost bytes for no signal beyond what
    the file extension already conveys."""
    (tmp_path / "a.py").write_text("x = 1\n")
    (tmp_path / "b.txt").write_text("hello\n")
    (tmp_path / "c.sh").write_text("#!/bin/sh\n")
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    for emoji in ("🐍", "📄", "🦀", "🟨", "🔵"):
        assert emoji not in out


def test_symbol_kind_not_repeated_as_word(tmp_path):
    """Functions/methods should be rendered with `()`, not the literal word
    'function ' / 'method ' on every line."""
    (tmp_path / "x.py").write_text(
        "def thing():\n"
        "    '''Do thing.'''\n"
        "    pass\n"
    )
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    if "## Key symbols" in out:
        block = out.split("## Key symbols", 1)[1]
        # No "function name" or "method name" patterns — the () suffix is enough.
        assert "- function " not in block
        assert "- method " not in block


def test_summary_line_collapses_languages(tmp_path):
    """Files / Symbols / Langs all live on one line so an N-language repo
    doesn't burn N+2 lines of header."""
    (tmp_path / "a.py").write_text("def f(): pass\n")
    (tmp_path / "b.sh").write_text("echo hi\n")
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    assert "Files:" in out
    # No standalone `## Languages` section — merged into the summary line.
    assert "## Languages" not in out
    assert "Langs:" in out


def test_top_dirs_collapses_to_one_line(tmp_path):
    (tmp_path / "pkg").mkdir()
    (tmp_path / "pkg" / "a.py").write_text("x = 1\n")
    (tmp_path / "pkg" / "b.py").write_text("y = 2\n")
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    if "Top dirs:" in out:
        # All entries on one line — no `## Top dirs` heading + bullet list.
        assert "## Top directories" not in out
        block = out.split("Top dirs:", 1)[1].split("\n", 1)[0]
        # The line should contain the directory once and at least one count.
        assert "pkg/" in block


def test_sessions_dir_is_skipped(tmp_path):
    """squishy's own session-storage directory shouldn't end up in the tree."""
    (tmp_path / "sessions").mkdir()
    (tmp_path / "sessions" / "abc123").mkdir()
    (tmp_path / "sessions" / "abc123" / "meta.json").write_text("{}")
    (tmp_path / "real.py").write_text("x = 1\n")
    out = generate_agents_md(_build(tmp_path), cwd=str(tmp_path))
    assert "sessions/" not in out
    assert "abc123" not in out
    assert "real.py" in out


def test_agents_md_permits_fallback_exploration():
    """Generated AGENTS.md must prefer recall but NOT forbid fallback tools —
    the never-block-exploration contract."""
    import os
    import tempfile

    from squishy.index import build_index
    from squishy.index.agents_md import generate_agents_md
    with tempfile.TemporaryDirectory() as tmp:
        with open(os.path.join(tmp, "m.py"), "w") as f:
            f.write('"""M."""\ndef f(): return 1\n')
        idx = build_index(tmp)
        md = generate_agents_md(idx, cwd=tmp)
    assert "fall back" in md.lower() or "fallback" in md.lower()
    assert "Do not call read_file, list_directory, or search_files without" not in md
